// <auto-generated>
// Default story expression enum. Use Tools > Story > Expression Enum Generator to update this list.
// </auto-generated>

namespace _00._Work.CheolYee._02._Scripts.Story.RuntIme.Shared.Types
{
    public enum StoryExpressionType
    {
        Neutral = 0,
        Happy = 1,
        Sad = 2,
        Angry = 3,
        Surprised = 4,
        Embarrassed = 5,
    }
}
